name: Build
description: Build tag and optionally push container images
inputs:
  name:
    required: true
    type: string
  target:
    required: false
    type: string
  file:
    required: false
    type: string
  context:
    required: false
    type: string
    default: '.'
  build-args:
    required: false
    type: string
  push:
    required: false
    type: boolean
    default: false
runs:
  using: "composite"
  steps:
    - name: Extract metadata for ${{ inputs.name }}
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ github.repository }}
        flavor: latest=false
        tags: |
          type=semver,pattern={{version}},prefix=${{ inputs.name }}-
          type=ref,event=branch,prefix=${{ inputs.name }}-
          type=sha,prefix=${{ inputs.name }}-
    - name: Build ${{ inputs.name }}
      uses: docker/build-push-action@v4
      with:
        context: ${{ inputs.context }}
        cache-from: type=gha,scope=${{ inputs.name }}
        cache-to: type=gha,mode=max,scope=${{ inputs.name }}
        push: ${{ inputs.push }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        file: ${{ inputs.file }}
        target: ${{ inputs.target }}
        build-args: ${{ inputs.build-args }}
