// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/filecoin-project/boost/sectorstatemgr (interfaces: StorageAPI)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	storiface "github.com/filecoin-project/lotus/storage/sealer/storiface"
	gomock "github.com/golang/mock/gomock"
)

// MockStorageAPI is a mock of StorageAPI interface.
type MockStorageAPI struct {
	ctrl     *gomock.Controller
	recorder *MockStorageAPIMockRecorder
}

// MockStorageAPIMockRecorder is the mock recorder for MockStorageAPI.
type MockStorageAPIMockRecorder struct {
	mock *MockStorageAPI
}

// NewMockStorageAPI creates a new mock instance.
func NewMockStorageAPI(ctrl *gomock.Controller) *MockStorageAPI {
	mock := &MockStorageAPI{ctrl: ctrl}
	mock.recorder = &MockStorageAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageAPI) EXPECT() *MockStorageAPIMockRecorder {
	return m.recorder
}

// StorageList mocks base method.
func (m *MockStorageAPI) StorageList(arg0 context.Context) (map[storiface.ID][]storiface.Decl, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StorageList", arg0)
	ret0, _ := ret[0].(map[storiface.ID][]storiface.Decl)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StorageList indicates an expected call of StorageList.
func (mr *MockStorageAPIMockRecorder) StorageList(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StorageList", reflect.TypeOf((*MockStorageAPI)(nil).StorageList), arg0)
}

// StorageRedeclareLocal mocks base method.
func (m *MockStorageAPI) StorageRedeclareLocal(arg0 context.Context, arg1 *storiface.ID, arg2 bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StorageRedeclareLocal", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// StorageRedeclareLocal indicates an expected call of StorageRedeclareLocal.
func (mr *MockStorageAPIMockRecorder) StorageRedeclareLocal(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StorageRedeclareLocal", reflect.TypeOf((*MockStorageAPI)(nil).StorageRedeclareLocal), arg0, arg1, arg2)
}
