name: 'Download Params'
description: 'Restore and fetch Filecoin proof parameters'

runs:
  using: 'composite'
  steps:
    - name: Run boostci
      run: make boostci
      shell: bash

    - name: Fetch parameters
      run: ./boostci fetch-params 8388608
      shell: bash

    - name: Save parameters cache
      uses: actions/cache@v2
      with:
        path: /var/tmp/filecoin-proof-parameters/
        key: v25-8mb-lotus-params-${{ github.sha }}
