name: "Bug Report"
description: "File a bug report to help us improve"
labels: [need/triage, kind/bug]
body:
- type: checkboxes
  attributes:
    label: Checklist
    description: Please check off the following boxes before continuing to file a bug report!
    options:
      - label: This is **not** a question or a support request. If you have any boost related questions, please ask in the [discussion forum](https://github.com/filecoin-project/boost/discussions).
        required: true
      - label: This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/boost/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
        required: true
      - label: This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/boost/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
        required: true
      - label: I **have** searched on the [issue tracker](https://github.com/filecoin-project/boost/issues) and the [discussion forum](https://github.com/filecoin-project/boost/discussions), and there is no existing related issue or discussion.
        required: true
      - label: I am running the [`Latest release`](https://github.com/filecoin-project/boost/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
        required: true
      - label: I did not make any code changes to boost.
        required: false
- type: checkboxes
  attributes:
    label: Boost component
    description: Please select the boost component you are filing a bug for
    options:
      - label: boost daemon - storage providers
        required: false
      - label: boost client
        required: false
      - label: boost UI
        required: false
      - label: boost data-transfer
        required: false
      - label: boost index-provider
        required: false
      - label:  Other
        required: false
- type: textarea
  id: version
  attributes:
    label: Boost Version
    render: text
    description: Enter the output of `boost --version` and `boostd --version` if applicable.
    placeholder: |
      e.g. 
      Daemon: boostd version 0.0.1+git.b27fec5 
      Client: boost version 0.0.1+git.b27fec5
  validations:
    required: true
- type: textarea
  id: Description
  attributes:
    label: Describe the Bug
    description: |
      This is where you get to tell us what went wrong, when doing so, please try to provide a clear and concise description of the bug with all related information:
      * What you were doding when you experienced the bug?
      * Any *error* messages you saw, *where* you saw them, and what you believe may have caused them (if you have any ideas).
      * What is the expected behaviour?
      * For deal making issues, include the deal logs from the boost UI.
  validations:
    required: true
- type: textarea
  id: extraInfo
  attributes:
    label: Logging Information
    render: text
    description: |
      Please provide debug logs of the problem, remember you can get set log level control for:
      * boostd: use `boostd log list` to get all log systems available and set level by `boostd log set-level`.
  validations:
    required: true
- type: textarea
  id: RepoSteps
  attributes:
    label: Repo Steps
    description: "Steps to reproduce the behavior"
    value: |
      1. Run '...'
      2. Do '...'
      3. See error '...'
      ...
  validations:
    required: false

