name: 'Setup Go'
description: 'Setup Go environment'

inputs:
  go-version:
    description: 'Go version to use'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}
