// Code generated by github.com/whyrusleeping/cbor-gen. DO NOT EDIT.

package message1_1

import (
	"fmt"
	"io"
	"math"
	"sort"

	datatransfer "github.com/filecoin-project/boost/datatransfer"
	cid "github.com/ipfs/go-cid"
	cbg "github.com/whyrusleeping/cbor-gen"
	xerrors "golang.org/x/xerrors"
)

var _ = xerrors.Errorf
var _ = cid.Undef
var _ = math.E
var _ = sort.Sort

func (t *TransferRequest1_1) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write([]byte{170}); err != nil {
		return err
	}

	// t.BCid (cid.Cid) (struct)
	if len("BCid") > cbg.MaxLength {
		return xerrors.Errorf("Value in field \"BCid\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("BCid"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("BCid")); err != nil {
		return err
	}

	if t.BCid == nil {
		if _, err := cw.Write(cbg.CborNull); err != nil {
			return err
		}
	} else {
		if err := cbg.WriteCid(cw, *t.BCid); err != nil {
			return xerrors.Errorf("failed to write cid field t.BCid: %w", err)
		}
	}

	// t.Part (bool) (bool)
	if len("Part") > cbg.MaxLength {
		return xerrors.Errorf("Value in field \"Part\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("Part"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("Part")); err != nil {
		return err
	}

	if err := cbg.WriteBool(w, t.Part); err != nil {
		return err
	}

	// t.Paus (bool) (bool)
	if len("Paus") > cbg.MaxLength {
		return xerrors.Errorf("Value in field \"Paus\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("Paus"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("Paus")); err != nil {
		return err
	}

	if err := cbg.WriteBool(w, t.Paus); err != nil {
		return err
	}

	// t.Pull (bool) (bool)
	if len("Pull") > cbg.MaxLength {
		return xerrors.Errorf("Value in field \"Pull\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("Pull"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("Pull")); err != nil {
		return err
	}

	if err := cbg.WriteBool(w, t.Pull); err != nil {
		return err
	}

	// t.Stor (typegen.Deferred) (struct)
	if len("Stor") > cbg.MaxLength {
		return xerrors.Errorf("Value in field \"Stor\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("Stor"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("Stor")); err != nil {
		return err
	}

	if err := t.Stor.MarshalCBOR(cw); err != nil {
		return err
	}

	// t.Type (uint64) (uint64)
	if len("Type") > cbg.MaxLength {
		return xerrors.Errorf("Value in field \"Type\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("Type"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("Type")); err != nil {
		return err
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.Type)); err != nil {
		return err
	}

	// t.VTyp (datatransfer.TypeIdentifier) (string)
	if len("VTyp") > cbg.MaxLength {
		return xerrors.Errorf("Value in field \"VTyp\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("VTyp"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("VTyp")); err != nil {
		return err
	}

	if len(t.VTyp) > cbg.MaxLength {
		return xerrors.Errorf("Value in field t.VTyp was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(t.VTyp))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string(t.VTyp)); err != nil {
		return err
	}

	// t.Vouch (typegen.Deferred) (struct)
	if len("Vouch") > cbg.MaxLength {
		return xerrors.Errorf("Value in field \"Vouch\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("Vouch"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("Vouch")); err != nil {
		return err
	}

	if err := t.Vouch.MarshalCBOR(cw); err != nil {
		return err
	}

	// t.XferID (uint64) (uint64)
	if len("XferID") > cbg.MaxLength {
		return xerrors.Errorf("Value in field \"XferID\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("XferID"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("XferID")); err != nil {
		return err
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.XferID)); err != nil {
		return err
	}

	// t.RestartChannel (datatransfer.ChannelID) (struct)
	if len("RestartChannel") > cbg.MaxLength {
		return xerrors.Errorf("Value in field \"RestartChannel\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("RestartChannel"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("RestartChannel")); err != nil {
		return err
	}

	if err := t.RestartChannel.MarshalCBOR(cw); err != nil {
		return err
	}
	return nil
}

func (t *TransferRequest1_1) UnmarshalCBOR(r io.Reader) (err error) {
	*t = TransferRequest1_1{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajMap {
		return fmt.Errorf("cbor input should be of type map")
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("TransferRequest1_1: map struct too large (%d)", extra)
	}

	var name string
	n := extra

	for i := uint64(0); i < n; i++ {

		{
			sval, err := cbg.ReadString(cr)
			if err != nil {
				return err
			}

			name = string(sval)
		}

		switch name {
		// t.BCid (cid.Cid) (struct)
		case "BCid":

			{

				b, err := cr.ReadByte()
				if err != nil {
					return err
				}
				if b != cbg.CborNull[0] {
					if err := cr.UnreadByte(); err != nil {
						return err
					}

					c, err := cbg.ReadCid(cr)
					if err != nil {
						return xerrors.Errorf("failed to read cid field t.BCid: %w", err)
					}

					t.BCid = &c
				}

			}
			// t.Part (bool) (bool)
		case "Part":

			maj, extra, err = cr.ReadHeader()
			if err != nil {
				return err
			}
			if maj != cbg.MajOther {
				return fmt.Errorf("booleans must be major type 7")
			}
			switch extra {
			case 20:
				t.Part = false
			case 21:
				t.Part = true
			default:
				return fmt.Errorf("booleans are either major type 7, value 20 or 21 (got %d)", extra)
			}
			// t.Paus (bool) (bool)
		case "Paus":

			maj, extra, err = cr.ReadHeader()
			if err != nil {
				return err
			}
			if maj != cbg.MajOther {
				return fmt.Errorf("booleans must be major type 7")
			}
			switch extra {
			case 20:
				t.Paus = false
			case 21:
				t.Paus = true
			default:
				return fmt.Errorf("booleans are either major type 7, value 20 or 21 (got %d)", extra)
			}
			// t.Pull (bool) (bool)
		case "Pull":

			maj, extra, err = cr.ReadHeader()
			if err != nil {
				return err
			}
			if maj != cbg.MajOther {
				return fmt.Errorf("booleans must be major type 7")
			}
			switch extra {
			case 20:
				t.Pull = false
			case 21:
				t.Pull = true
			default:
				return fmt.Errorf("booleans are either major type 7, value 20 or 21 (got %d)", extra)
			}
			// t.Stor (typegen.Deferred) (struct)
		case "Stor":

			{

				t.Stor = new(cbg.Deferred)

				if err := t.Stor.UnmarshalCBOR(cr); err != nil {
					return xerrors.Errorf("failed to read deferred field: %w", err)
				}
			}
			// t.Type (uint64) (uint64)
		case "Type":

			{

				maj, extra, err = cr.ReadHeader()
				if err != nil {
					return err
				}
				if maj != cbg.MajUnsignedInt {
					return fmt.Errorf("wrong type for uint64 field")
				}
				t.Type = uint64(extra)

			}
			// t.VTyp (datatransfer.TypeIdentifier) (string)
		case "VTyp":

			{
				sval, err := cbg.ReadString(cr)
				if err != nil {
					return err
				}

				t.VTyp = datatransfer.TypeIdentifier(sval)
			}
			// t.Vouch (typegen.Deferred) (struct)
		case "Vouch":

			{

				t.Vouch = new(cbg.Deferred)

				if err := t.Vouch.UnmarshalCBOR(cr); err != nil {
					return xerrors.Errorf("failed to read deferred field: %w", err)
				}
			}
			// t.XferID (uint64) (uint64)
		case "XferID":

			{

				maj, extra, err = cr.ReadHeader()
				if err != nil {
					return err
				}
				if maj != cbg.MajUnsignedInt {
					return fmt.Errorf("wrong type for uint64 field")
				}
				t.XferID = uint64(extra)

			}
			// t.RestartChannel (datatransfer.ChannelID) (struct)
		case "RestartChannel":

			{

				if err := t.RestartChannel.UnmarshalCBOR(cr); err != nil {
					return xerrors.Errorf("unmarshaling t.RestartChannel: %w", err)
				}

			}

		default:
			// Field doesn't exist on this type, so ignore it
			cbg.ScanForLinks(r, func(cid.Cid) {})
		}
	}

	return nil
}
