{
 "title": "Boostd",
 "description": "All panels related to boostd service",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Boostd Services",
   "type": "timeseries",
   "description": "Uptime for the Boostd service",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "boost_info{node_type=\"boostd\"}"
    }
   ]
  },
  {
   "title": "API Query Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "irate(boost_api_request_duration_ms_count{api=\"boost\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Graphsync Retrievals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Graphsync Bytes Served",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(boost_graphsync_request_bytes_sent_count{}[$__rate_interval]) * 15",
     "legendFormat": "total"
    },
    {
     "expr": "irate(boost_graphsync_request_bytes_sent_unpaid_count{}[$__rate_interval]) * 15",
     "legendFormat": "unpaid"
    },
    {
     "expr": "irate(boost_graphsync_request_bytes_sent_paid_count{}[$__rate_interval]) * 15",
     "legendFormat": "paid"
    }
   ]
  },
  {
   "title": "Graphsync Blocks Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "irate(boost_graphsync_request_block_sent_count{}[$__rate_interval]) * 15",
     "legendFormat": "total"
    },
    {
     "expr": "irate(boost_graphsync_request_block_sent_unpaid_count{}[$__rate_interval]) * 15",
     "legendFormat": "unpaid"
    },
    {
     "expr": "irate(boost_graphsync_request_block_sent_paid_count{}[$__rate_interval]) * 15",
     "legendFormat": "paid"
    }
   ]
  },
  {
   "title": "Graphsync Transfers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "expr": "irate(boost_graphsync_request_queued_count{}[$__rate_interval]) * 15",
     "legendFormat": "queued"
    },
    {
     "expr": "irate(boost_graphsync_request_started_count{}[$__rate_interval]) * 15",
     "legendFormat": "started"
    },
    {
     "expr": "irate(boost_graphsync_request_completed_count{}[$__rate_interval]) * 15",
     "legendFormat": "completed"
    },
    {
     "expr": "irate(boost_graphsync_request_client_cancelled_count{}[$__rate_interval]) * 15",
     "legendFormat": "client_cancelled"
    },
    {
     "expr": "irate(boost_graphsync_request_completed_unpaid_success_count{}[$__rate_interval]) * 15",
     "legendFormat": "completed success"
    },
    {
     "expr": "irate(boost_graphsync_request_completed_unpaid_fail_count{}[$__rate_interval]) * 15",
     "legendFormat": "completed failed"
    }
   ]
  },
  {
   "title": "Graphsync Network Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "targets": [
    {
     "expr": "irate(boost_graphsync_request_network_error_count{}[$__rate_interval]) * 15",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Piece Reader", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "PR Init Count",
   "type": "timeseries",
   "description": "PieceReader init count",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "irate(boost_dagstore_pr_init_count{job=~\"boost\", host=~\"$host\"}[$__rate_interval]) * 15",
     "legendFormat": "Init Count"
    }
   ]
  },
  {
   "title": "PR Requested Bytes",
   "type": "timeseries",
   "description": "PieceReader requested bytes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(boost_dagstore_pr_requested_bytes{job=~\"boost\", host=~\"$host\"}[$__rate_interval]) * 15",
     "legendFormat": "Requested Bytes"
    }
   ]
  },
  {
   "title": "PR Discard Count",
   "type": "timeseries",
   "description": "PieceReader discard count",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "irate(boost_dagstore_pr_discard_count{job=~\"boost\", host=~\"$host\"}[$__rate_interval]) * 15",
     "legendFormat": "Discarded"
    }
   ]
  },
  {
   "title": "PR Discarded Bytes",
   "type": "timeseries",
   "description": "PieceReader discarded bytes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(boost_dagstore_pr_discarded_bytes{job=~\"boost\", host=~\"$host\"}[$__rate_interval]) * 15",
     "legendFormat": "Discarded Bytes"
    }
   ]
  },
  {
   "title": "PR Seek Back Count",
   "type": "timeseries",
   "description": "PieceReader seek back count",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "irate(boost_dagstore_pr_seek_back_count{job=~\"boost\", host=~\"$host\"}[$__rate_interval]) * 15",
     "legendFormat": "Seek Backs"
    }
   ]
  },
  {
   "title": "PR Seek Back Bytes",
   "type": "timeseries",
   "description": "PieceReader seek back bytes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "irate(boost_dagstore_pr_seek_back_bytes{job=~\"boost\", host=~\"$host\"}[$__rate_interval]) * 15",
     "legendFormat": "Seek Back Bytes"
    }
   ]
  },
  {
   "title": "PR Seek Forward Count",
   "type": "timeseries",
   "description": "PieceReader seek forward count",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(boost_dagstore_pr_seek_forward_count{job=~\"boost\", host=~\"$host\"}[$__rate_interval]) * 15",
     "legendFormat": "Seek Back Bytes"
    }
   ]
  },
  {
   "title": "PR Seek Forward Bytes",
   "type": "timeseries",
   "description": "PieceReader seek forward bytes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(boost_dagstore_pr_seek_forward_bytes{job=~\"boost\", host=~\"$host\"}[$__rate_interval]) * 15",
     "legendFormat": "Seek Forward Bytes"
    }
   ]
  },
  { "title": "Service Internals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Memory in Off-Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_mspan_inuse_bytes{job=~\"boost\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{job=~\"boost\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_memstats_mcache_inuse_bytes{job=~\"boost\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{job=~\"boost\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_memstats_buck_hash_sys_bytes{job=~\"boost\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_memstats_gc_sys_bytes{job=~\"boost\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_memstats_other_sys_bytes{job=~\"boost\"} - go_memstats_other_sys_bytes{job=~\"boost\"}",
     "legendFormat": "bytes of memory used for other runtime allocations"
    },
    {
     "expr": "go_memstats_next_gc_bytes{job=~\"boost\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Memory in Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=~\"boost\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{job=~\"boost\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{job=~\"boost\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=~\"boost\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_memstats_heap_released_bytes{job=~\"boost\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Memory in Stack",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{job=~\"boost\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{job=~\"boost\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{job=~\"boost\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Number of Live Objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{job=~\"boost\"} - go_memstats_frees_total{job=~\"boost\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Objects Allocated",
   "type": "timeseries",
   "description": "shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{job=~\"boost\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Pointer Dereferences",
   "type": "timeseries",
   "description": "go_memstats_lookups_total – counts how many pointer dereferences happened. This is a counter value so you can use rate() to lookups/s.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(go_memstats_lookups_total{job=~\"boost\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{job=~\"boost\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rates of Allocation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=~\"boost\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC duration quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=~\"boost\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  }
 ]
}