{
 "title": "Booster HTTP",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Booster-HTTP Services",
   "type": "timeseries",
   "description": "Uptime for the Booster-HTTP service",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "booster_http_info" }
   ]
  },
  { "title": "booster-http: ipfs gateway", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Http Gateway Bytes Served",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(booster_http_http_rbls_bytes_sent_count{}[$__rate_interval]) * 15",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Http Gateway Block Get Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "irate(booster_http_http_rbls_get_request_count{}[$__rate_interval]) * 15",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Http Gateway Block Get Response Counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "targets": [
    {
     "expr": "irate(booster_http_http_rbls_get_success_response_count{}[$__rate_interval]) * 15",
     "legendFormat": "__auto"
    },
    {
     "expr": "irate(booster_http_http_rbls_get_fail_response_count{}[$__rate_interval]) * 15",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Http Block Get Success / Failure Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(irate(booster_http_http_rbls_get_success_response_count{}[$__rate_interval]) * 15) / (irate(booster_http_http_rbls_get_request_count{}[$__rate_interval]) * 15)",
     "legendFormat": "Success"
    },
    {
     "expr": "(irate(booster_http_http_rbls_get_fail_response_count{}[$__rate_interval]) * 15) / (irate(booster_http_http_rbls_get_request_count{}[$__rate_interval]) * 15)",
     "legendFormat": "Fail"
    }
   ]
  },
  { "title": "booster-http: piece retrievals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Piece by CID Status Response Counts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(booster_http_http_piece_by_cid_200_response_count{host=~\"$host\"}[$__rate_interval]) * 15",
     "legendFormat": "200"
    },
    {
     "expr": "irate(booster_http_http_piece_by_cid_400_response_count{host=~\"$host\"}[$__rate_interval]) * 15",
     "legendFormat": "400"
    },
    {
     "expr": "irate(booster_http_http_piece_by_cid_404_response_count{host=~\"$host\"}[$__rate_interval]) * 15",
     "legendFormat": "404"
    },
    {
     "expr": "irate(booster_http_http_piece_by_cid_500_response_count{host=~\"$host\"}[$__rate_interval]) * 15",
     "legendFormat": "500"
    }
   ]
  },
  {
   "title": "Piece by CID Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(booster_http_http_piece_by_cid_request_count{host=~\"$host\"}[$__rate_interval]) * 15",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Piece by CID Request Durations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(booster_http_http_piece_by_cid_request_duration_ms_bucket{host=~\"$host\"}[$__rate_interval]) * 15) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(booster_http_http_piece_by_cid_request_duration_ms_bucket{host=~\"$host\"}[$__rate_interval]) * 15) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.98, sum(irate(booster_http_http_piece_by_cid_request_duration_ms_bucket{host=~\"$host\"}[$__rate_interval]) * 15) by (le))",
     "legendFormat": "98%"
    }
   ]
  },
  { "title": "Service Internals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Memory in Off-Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_mspan_inuse_bytes{job=~\"booster-http\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{job=~\"booster-http\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_memstats_mcache_inuse_bytes{job=~\"booster-http\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{job=~\"booster-http\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_memstats_buck_hash_sys_bytes{job=~\"booster-http\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_memstats_gc_sys_bytes{job=~\"booster-http\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_memstats_other_sys_bytes{job=~\"booster-http\"} - go_memstats_other_sys_bytes{job=~\"booster-http\"}",
     "legendFormat": "bytes of memory used for other runtime allocations"
    },
    {
     "expr": "go_memstats_next_gc_bytes{job=~\"booster-http\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Memory in Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=~\"booster-http\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{job=~\"booster-http\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{job=~\"booster-http\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=~\"booster-http\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_memstats_heap_released_bytes{job=~\"booster-http\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Memory in Stack",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{job=~\"booster-http\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{job=~\"booster-http\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{job=~\"booster-http\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Number of Live Objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{job=~\"booster-http\"} - go_memstats_frees_total{job=~\"booster-http\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Objects Allocated",
   "type": "timeseries",
   "description": "shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{job=~\"booster-http\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Pointer Dereferences",
   "type": "timeseries",
   "description": "go_memstats_lookups_total – counts how many pointer dereferences happened. This is a counter value so you can use rate() to lookups/s.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(go_memstats_lookups_total{job=~\"booster-http\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{job=~\"booster-http\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rates of Allocation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=~\"booster-http\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC duration quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=~\"booster-http\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  }
 ]
}