{
 "title": "Boostd-data (LID)",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "boostd_data_success_add_deal_for_piece_count+boostd_data_success_add_index_count+boostd_data_success_is_indexed_count+boostd_data_success_is_complete_index_count+boostd_data_success_get_index_count+boostd_data_success_get_offset_size_count+boostd_data_success_list_pieces_count+boostd_data_success_piece_count_count+boostd_data_success_scan_progress_count+boostd_data_success_get_piece_metadata_count+boostd_data_success_get_piece_deals_count+boostd_data_success_indexed_at_count+boostd_data_success_pieces_containing_multihashes_count+boostd_data_success_remove_deal_for_piece_count+boostd_data_success_remove_piece_metadata_count+boostd_data_success_remove_indexes_count+boostd_data_success_next_pieces_to_check_count+boostd_data_success_flag_piece_count+boostd_data_success_unflag_piece_count+boostd_data_success_flagged_pieces_list_count+boostd_data_success_flagged_pieces_count_count\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Boost-data Service Uptime",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "boostd_data_info{node_type=\"boostd-data\"}"
    }
   ]
  },
  {
   "title": "Over All Suucessfull Queries",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(boostd_data_success_add_deal_for_piece_count[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "boostd_data_success_add_index_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "boostd_data_success_is_indexed_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "boostd_data_success_is_complete_index_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "boostd_data_success_get_index_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "boostd_data_success_get_offset_size_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "boostd_data_success_list_pieces_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "boostd_data_success_piece_count_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "boostd_data_success_scan_progress_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "boostd_data_success_get_piece_metadata_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "boostd_data_success_get_piece_deals_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "boostd_data_success_indexed_at_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "boostd_data_success_pieces_containing_multihashes_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "boostd_data_success_remove_deal_for_piece_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "boostd_data_success_remove_piece_metadata_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "boostd_data_success_remove_indexes_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "boostd_data_success_next_pieces_to_check_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "boostd_data_success_flag_piece_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "boostd_data_success_unflag_piece_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "boostd_data_success_flagged_pieces_list_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "boostd_data_success_flagged_pieces_count_count",
     "legendFormat": "__auto"
    },
    {
     "expression": "$A + $B + $C + $D + $E + $F + $G + $H + $I + $J + $K + $L + $M + $N + $O + $P + $Q + $R + $S + $T + $U",
     "type": "math"
    }
   ]
  },
  {
   "title": "Piece Containing multihashes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "boostd_data_success_pieces_containing_multihashes_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "boostd_data_failure_pieces_containing_multihashes_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "flagged pieced count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "boostd_data_success_flagged_pieces_count_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "boostd_data_failure_flagged_pieces_count_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Add Deal For Piece",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "boostd_data_success_add_deal_for_piece_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "boostd_data_failure_add_deal_for_piece_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "flagged piece list",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "boostd_data_success_flagged_pieces_list_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "boosdt_data_failure_flagged_pieces_list_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Is Indexed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "boostd_data_success_is_indexed_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "boostd_data_failure_is_indexed_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "unflag piece",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "boostd_data_success_unflag_piece_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "boostd_data_failure_unflag_piece_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "get offset size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "boostd_data_success_get_offset_size_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "boostd_data_failure_get_offset_size_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "flag piece",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "boostd_data_success_flag_piece_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "boostd_data_failure_flag_piece_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "is_complete",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "boostd_data_success_is_complete_index_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "boostd_data_failure_is_complete_index_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "next piece to check",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "boostd_data_success_next_pieces_to_check_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "boostd_data_failure_next_pieces_to_check_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "remove index",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "boostd_data_success_remove_indexes_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "boostd_data_failure_remove_indexes_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "remove poiece metadta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "boostd_data_success_remove_piece_metadata_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "boostd_data_failure_remove_piece_metadata_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "remove deal for piece",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "targets": [
    {
     "expr": "boostd_data_success_remove_deal_for_piece_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "boostd_data_failure_remove_deal_for_piece_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "indexed at",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "boostd_data_success_indexed_at_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "boostd_data_failure_indexed_at_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gete piece deals",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "targets": [
    {
     "expr": "boostd_data_success_get_piece_deals_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "boostd_data_failure_get_piece_deals_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "get piece metadata",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "boostd_data_success_get_piece_metadata_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "boostd_data_failure_get_piece_metadata_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "scan progress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "targets": [
    {
     "expr": "boostd_data_success_scan_progress_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "boostd_data_failure_scan_progress_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "piece count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "targets": [
    {
     "expr": "boostd_data_success_piece_count_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "boostd_data_failure_piece_count_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "list pieces",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "targets": [
    {
     "expr": "boostd_data_success_list_pieces_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "boostd_data_failure_list_pieces_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "get index",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "targets": [
    {
     "expr": "boostd_data_success_get_index_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "boostd_data_failure_get_index_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Add Index",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
   "targets": [
    {
     "expr": "boostd_data_success_add_index_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "boostd_data_failure_add_index_count",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}