{
 "title": "Retrievals",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "boost", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API Request Durations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(boost_api_request_duration_ms_bucket{job=\"boost\"}[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "boost | Runtime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory in Off-Heap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "go_memstats_mspan_inuse_bytes{job=~\"boost\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "go_memstats_mspan_sys_bytes{job=~\"boost\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "go_memstats_mcache_inuse_bytes{job=~\"boost\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "go_memstats_mcache_sys_bytes{job=~\"boost\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "go_memstats_buck_hash_sys_bytes{job=~\"boost\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "go_memstats_gc_sys_bytes{job=~\"boost\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "go_memstats_other_sys_bytes{job=~\"boost\"} - go_memstats_other_sys_bytes{job=~\"boost\"}",
       "legendFormat": "bytes of memory used for other runtime allocations"
      },
      {
       "expr": "go_memstats_next_gc_bytes{job=~\"boost\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Memory in Heap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{job=~\"boost\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "go_memstats_heap_sys_bytes{job=~\"boost\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "go_memstats_heap_idle_bytes{job=~\"boost\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "go_memstats_heap_inuse_bytes{job=~\"boost\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "go_memstats_heap_released_bytes{job=~\"boost\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Memory in Stack",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_stack_inuse_bytes{job=~\"boost\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "go_memstats_stack_sys_bytes{job=~\"boost\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Total Used Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "go_memstats_sys_bytes{job=~\"boost\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Number of Live Objects",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_memstats_mallocs_total{job=~\"boost\"} - go_memstats_frees_total{job=~\"boost\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rate of Objects Allocated",
     "type": "timeseries",
     "description": "shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(go_memstats_mallocs_total{job=~\"boost\"}[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rate of Pointer Dereferences",
     "type": "timeseries",
     "description": "go_memstats_lookups_total – counts how many pointer dereferences happened. This is a counter value so you can use rate() to lookups/s.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(go_memstats_lookups_total{job=~\"boost\"}[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_goroutines{job=~\"boost\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rates of Allocation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(go_memstats_alloc_bytes_total{job=~\"boost\"}[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GC duration quantile",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "go_gc_duration_seconds{job=~\"boost\"}",
       "legendFormat": "{{quantile}}"
      }
     ]
    }
   ]
  },
  { "title": "booster-http", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Payload by CID Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(booster_http_http_payload_by_cid_request_count{}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Piece by CID Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(booster_http_http_piece_by_cid_request_count{}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Payload by CID Status Response Counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(booster_http_http_payload_by_cid_200_response_count{}[$__rate_interval]))",
     "legendFormat": "200 | Ok"
    },
    {
     "expr": "sum(rate(booster_http_http_payload_by_cid_400_response_count{}[$__rate_interval]))",
     "legendFormat": "400 | Bad Request"
    },
    {
     "expr": "sum(rate(booster_http_http_payload_by_cid_404_response_count{}[$__rate_interval]))",
     "legendFormat": "404 | Not Found"
    },
    {
     "expr": "sum(rate(booster_http_http_payload_by_cid_500_response_count{}[$__rate_interval]))",
     "legendFormat": "500 | Internal Server Error"
    }
   ]
  },
  {
   "title": "Piece by CID Status Response Counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(booster_http_http_piece_by_cid_200_response_count{}[$__rate_interval]))",
     "legendFormat": "200 | Ok"
    },
    {
     "expr": "sum(rate(booster_http_http_piece_by_cid_400_response_count{}[$__rate_interval]))",
     "legendFormat": "400 | Bad Request"
    },
    {
     "expr": "sum(rate(booster_http_http_piece_by_cid_404_response_count{}[$__rate_interval]))",
     "legendFormat": "404 | Not Found"
    },
    {
     "expr": "sum(rate(booster_http_http_piece_by_cid_500_response_count{}[$__rate_interval]))",
     "legendFormat": "500 | Internal Server Error"
    }
   ]
  },
  {
   "title": "Payload by CID Request Durations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(booster_http_http_payload_by_cid_request_duration_ms_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Piece by CID Request Durations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(booster_http_http_piece_by_cid_request_duration_ms_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "booster-http | Runtime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory in Off-Heap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "go_memstats_mspan_inuse_bytes{job=~\"booster-http\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "go_memstats_mspan_sys_bytes{job=~\"booster-http\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "go_memstats_mcache_inuse_bytes{job=~\"booster-http\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "go_memstats_mcache_sys_bytes{job=~\"booster-http\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "go_memstats_buck_hash_sys_bytes{job=~\"booster-http\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "go_memstats_gc_sys_bytes{job=~\"booster-http\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "go_memstats_other_sys_bytes{job=~\"booster-http\"} - go_memstats_other_sys_bytes{job=~\"booster-http\"}",
       "legendFormat": "bytes of memory used for other runtime allocations"
      },
      {
       "expr": "go_memstats_next_gc_bytes{job=~\"booster-http\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Memory in Heap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{job=~\"booster-http\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "go_memstats_heap_sys_bytes{job=~\"booster-http\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "go_memstats_heap_idle_bytes{job=~\"booster-http\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "go_memstats_heap_inuse_bytes{job=~\"booster-http\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "go_memstats_heap_released_bytes{job=~\"booster-http\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Memory in Stack",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_stack_inuse_bytes{job=~\"booster-http\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "go_memstats_stack_sys_bytes{job=~\"booster-http\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Total Used Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "go_memstats_sys_bytes{job=~\"booster-http\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Number of Live Objects",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_memstats_mallocs_total{job=~\"booster-http\"} - go_memstats_frees_total{job=~\"booster-http\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rate of Objects Allocated",
     "type": "timeseries",
     "description": "shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(go_memstats_mallocs_total{job=~\"booster-http\"}[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rate of Pointer Dereferences",
     "type": "timeseries",
     "description": "go_memstats_lookups_total – counts how many pointer dereferences happened. This is a counter value so you can use rate() to lookups/s.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(go_memstats_lookups_total{job=~\"booster-http\"}[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_goroutines{job=~\"booster-http\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rates of Allocation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(go_memstats_alloc_bytes_total{job=~\"booster-http\"}[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GC duration quantile",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "go_gc_duration_seconds{job=~\"booster-http\"}",
       "legendFormat": "{{quantile}}"
      }
     ]
    }
   ]
  }
 ]
}