{
 "title": "Provider Retrievals",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "host", "query": { "query": "label_values(host)" } }
  ]
 },
 "panels": [
  { "title": "boost", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API Request Durations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(boost_api_request_duration_ms_bucket{job=\"boost\", host=~\"$host\"}[$__rate_interval]) * 15) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(boost_api_request_duration_ms_bucket{job=\"boost\", host=~\"$host\"}[$__rate_interval]) * 15) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.98, sum(irate(boost_api_request_duration_ms_bucket{job=\"boost\", host=~\"$host\"}[$__rate_interval]) * 15) by (le))",
     "legendFormat": "98%"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{job=~\"boost\", host=~\"$host\"}",
     "legendFormat": "Goroutines"
    }
   ]
  },
  { "title": "graphsync", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Graphsync Bytes Served",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(boost_graphsync_request_bytes_sent_count{}[$__rate_interval]) * 15",
     "legendFormat": "total"
    },
    {
     "expr": "irate(boost_graphsync_request_bytes_sent_unpaid_count{}[$__rate_interval]) * 15",
     "legendFormat": "unpaid"
    },
    {
     "expr": "irate(boost_graphsync_request_bytes_sent_paid_count{}[$__rate_interval]) * 15",
     "legendFormat": "paid"
    }
   ]
  },
  {
   "title": "Graphsync Blocks Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "irate(boost_graphsync_request_block_sent_count{}[$__rate_interval]) * 15",
     "legendFormat": "total"
    },
    {
     "expr": "irate(boost_graphsync_request_block_sent_unpaid_count{}[$__rate_interval]) * 15",
     "legendFormat": "unpaid"
    },
    {
     "expr": "irate(boost_graphsync_request_block_sent_paid_count{}[$__rate_interval]) * 15",
     "legendFormat": "paid"
    }
   ]
  },
  {
   "title": "Graphsync Transfers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "targets": [
    {
     "expr": "irate(boost_graphsync_request_queued_count{}[$__rate_interval]) * 15",
     "legendFormat": "queued"
    },
    {
     "expr": "irate(boost_graphsync_request_started_count{}[$__rate_interval]) * 15",
     "legendFormat": "started"
    },
    {
     "expr": "irate(boost_graphsync_request_completed_count{}[$__rate_interval]) * 15",
     "legendFormat": "completed"
    },
    {
     "expr": "irate(boost_graphsync_request_client_cancelled_count{}[$__rate_interval]) * 15",
     "legendFormat": "client_cancelled"
    },
    {
     "expr": "irate(boost_graphsync_request_completed_unpaid_success_count{}[$__rate_interval]) * 15",
     "legendFormat": "completed success"
    },
    {
     "expr": "irate(boost_graphsync_request_completed_unpaid_fail_count{}[$__rate_interval]) * 15",
     "legendFormat": "completed failed"
    }
   ]
  },
  {
   "title": "Graphsync Network Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "irate(boost_graphsync_request_network_error_count{}[$__rate_interval]) * 15",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "booster-bitswap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Bitswap Bytes Served",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "irate(booster_bitswap_bitswap_rbls_bytes_sent_count{}[$__rate_interval]) * 15",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bitswap Block Get Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "irate(booster_bitswap_bitswap_rbls_get_request_count{}[$__rate_interval]) * 15",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bitswap Block Get Response Counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "targets": [
    {
     "expr": "irate(booster_bitswap_bitswap_rbls_get_success_response_count{}[$__rate_interval]) * 15",
     "legendFormat": "__auto"
    },
    {
     "expr": "irate(booster_bitswap_bitswap_rbls_get_fail_response_count{}[$__rate_interval]) * 15",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bitswap Block Get Success / Failure Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(irate(booster_bitswap_bitswap_rbls_get_success_response_count{}[$__rate_interval]) * 15) / (irate(booster_bitswap_bitswap_rbls_get_request_count{}[$__rate_interval]) * 15)",
     "legendFormat": "Success"
    },
    {
     "expr": "(irate(booster_bitswap_bitswap_rbls_get_fail_response_count{}[$__rate_interval]) * 15) / (irate(booster_bitswap_bitswap_rbls_get_request_count{}[$__rate_interval]) * 15)",
     "legendFormat": "Fail"
    }
   ]
  },
  {
   "title": "Bitswap Block GetSize Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "irate(booster_bitswap_bitswap_rbls_getsize_request_count{}[$__rate_interval]) * 15",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bitswap Block GetSize Response Counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
   "targets": [
    {
     "expr": "irate(booster_bitswap_bitswap_rbls_getsize_success_response_count{}[$__rate_interval]) * 15",
     "legendFormat": "__auto"
    },
    {
     "expr": "irate(booster_bitswap_bitswap_rbls_getsize_fail_response_count{}[$__rate_interval]) * 15",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bitswap Block GetSize Success / Failure Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(irate(booster_bitswap_bitswap_rbls_getsize_success_response_count{}[$__rate_interval]) * 15) / (irate(booster_bitswap_bitswap_rbls_getsize_request_count{}[$__rate_interval]) * 15)",
     "legendFormat": "Success"
    },
    {
     "expr": "(irate(booster_bitswap_bitswap_rbls_getsize_fail_response_count{}[$__rate_interval]) * 15) / (irate(booster_bitswap_bitswap_rbls_getsize_fail_count{}[$__rate_interval]) * 15)",
     "legendFormat": "Fail"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "go_goroutines{job=\"booster-bitswap\", host=~\"$host\"}",
     "legendFormat": "Goroutines"
    }
   ]
  },
  { "title": "booster-http: ipfs gateway", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Http Gateway Bytes Served",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(booster_http_http_rbls_bytes_sent_count{}[$__rate_interval]) * 15",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Http Gateway Block Get Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "irate(booster_http_http_rbls_get_request_count{}[$__rate_interval]) * 15",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Http Gateway Block Get Response Counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 66 },
   "targets": [
    {
     "expr": "irate(booster_http_http_rbls_get_success_response_count{}[$__rate_interval]) * 15",
     "legendFormat": "__auto"
    },
    {
     "expr": "irate(booster_http_http_rbls_get_fail_response_count{}[$__rate_interval]) * 15",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Http Block Get Success / Failure Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(irate(booster_http_http_rbls_get_success_response_count{}[$__rate_interval]) * 15) / (irate(booster_http_http_rbls_get_request_count{}[$__rate_interval]) * 15)",
     "legendFormat": "Success"
    },
    {
     "expr": "(irate(booster_http_http_rbls_get_fail_response_count{}[$__rate_interval]) * 15) / (irate(booster_http_http_rbls_get_request_count{}[$__rate_interval]) * 15)",
     "legendFormat": "Fail"
    }
   ]
  },
  { "title": "booster-http", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{job=~\"booster-http\", host=~\"$host\"}",
     "legendFormat": "Goroutines"
    }
   ]
  },
  {
   "title": "Piece by CID Status Response Counts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(booster_http_http_piece_by_cid_200_response_count{host=~\"$host\"}[$__rate_interval]) * 15",
     "legendFormat": "200"
    },
    {
     "expr": "irate(booster_http_http_piece_by_cid_400_response_count{host=~\"$host\"}[$__rate_interval]) * 15",
     "legendFormat": "400"
    },
    {
     "expr": "irate(booster_http_http_piece_by_cid_404_response_count{host=~\"$host\"}[$__rate_interval]) * 15",
     "legendFormat": "404"
    },
    {
     "expr": "irate(booster_http_http_piece_by_cid_500_response_count{host=~\"$host\"}[$__rate_interval]) * 15",
     "legendFormat": "500"
    }
   ]
  },
  {
   "title": "Piece by CID Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(booster_http_http_piece_by_cid_request_count{host=~\"$host\"}[$__rate_interval]) * 15",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Piece by CID Request Durations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(booster_http_http_piece_by_cid_request_duration_ms_bucket{host=~\"$host\"}[$__rate_interval]) * 15) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(booster_http_http_piece_by_cid_request_duration_ms_bucket{host=~\"$host\"}[$__rate_interval]) * 15) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.98, sum(irate(booster_http_http_piece_by_cid_request_duration_ms_bucket{host=~\"$host\"}[$__rate_interval]) * 15) by (le))",
     "legendFormat": "98%"
    }
   ]
  },
  { "title": "dagstore", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "Dagstore PR Init Count",
   "type": "timeseries",
   "description": "PieceReader init count",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "targets": [
    {
     "expr": "irate(boost_dagstore_pr_init_count{job=~\"boost\", host=~\"$host\"}[$__rate_interval]) * 15",
     "legendFormat": "Init Count"
    }
   ]
  },
  {
   "title": "Dagstore PR Requested Bytes",
   "type": "timeseries",
   "description": "PieceReader requested bytes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(boost_dagstore_pr_requested_bytes{job=~\"boost\", host=~\"$host\"}[$__rate_interval]) * 15",
     "legendFormat": "Requested Bytes"
    }
   ]
  },
  {
   "title": "Dagstore PR Discard Count",
   "type": "timeseries",
   "description": "PieceReader discard count",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "targets": [
    {
     "expr": "irate(boost_dagstore_pr_discard_count{job=~\"boost\", host=~\"$host\"}[$__rate_interval]) * 15",
     "legendFormat": "Discarded"
    }
   ]
  },
  {
   "title": "Dagstore PR Discarded Bytes",
   "type": "timeseries",
   "description": "PieceReader discarded bytes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(boost_dagstore_pr_discarded_bytes{job=~\"boost\", host=~\"$host\"}[$__rate_interval]) * 15",
     "legendFormat": "Discarded Bytes"
    }
   ]
  },
  {
   "title": "Dagstore PR Seek Back Count",
   "type": "timeseries",
   "description": "PieceReader seek back count",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "targets": [
    {
     "expr": "irate(boost_dagstore_pr_seek_back_count{job=~\"boost\", host=~\"$host\"}[$__rate_interval]) * 15",
     "legendFormat": "Seek Backs"
    }
   ]
  },
  {
   "title": "Dagstore PR Seek Back Bytes",
   "type": "timeseries",
   "description": "PieceReader seek back bytes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
   "targets": [
    {
     "expr": "irate(boost_dagstore_pr_seek_back_bytes{job=~\"boost\", host=~\"$host\"}[$__rate_interval]) * 15",
     "legendFormat": "Seek Back Bytes"
    }
   ]
  },
  {
   "title": "Dagstore PR Seek Forward Count",
   "type": "timeseries",
   "description": "PieceReader seek forward count",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(boost_dagstore_pr_seek_forward_count{job=~\"boost\", host=~\"$host\"}[$__rate_interval]) * 15",
     "legendFormat": "Seek Back Bytes"
    }
   ]
  },
  {
   "title": "Dagstore PR Seek Forward Bytes",
   "type": "timeseries",
   "description": "PieceReader seek forward bytes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(boost_dagstore_pr_seek_forward_bytes{job=~\"boost\", host=~\"$host\"}[$__rate_interval]) * 15",
     "legendFormat": "Seek Forward Bytes"
    }
   ]
  }
 ]
}