{
 "title": "Provider Runtimes",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "host", "query": { "query": "label_values(host)" } }
  ]
 },
 "panels": [
  { "title": "boostd", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory in Off-Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_mspan_inuse_bytes{job=~\"boost\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{job=~\"boost\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_memstats_mcache_inuse_bytes{job=~\"boost\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{job=~\"boost\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_memstats_buck_hash_sys_bytes{job=~\"boost\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_memstats_gc_sys_bytes{job=~\"boost\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_memstats_other_sys_bytes{job=~\"boost\"} - go_memstats_other_sys_bytes{job=~\"boost\"}",
     "legendFormat": "bytes of memory used for other runtime allocations"
    },
    {
     "expr": "go_memstats_next_gc_bytes{job=~\"boost\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Memory in Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=~\"boost\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{job=~\"boost\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{job=~\"boost\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=~\"boost\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_memstats_heap_released_bytes{job=~\"boost\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Memory in Stack",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{job=~\"boost\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{job=~\"boost\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{job=~\"boost\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Number of Live Objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{job=~\"boost\"} - go_memstats_frees_total{job=~\"boost\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Objects Allocated",
   "type": "timeseries",
   "description": "shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{job=~\"boost\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Pointer Dereferences",
   "type": "timeseries",
   "description": "go_memstats_lookups_total – counts how many pointer dereferences happened. This is a counter value so you can use rate() to lookups/s.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(go_memstats_lookups_total{job=~\"boost\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{job=~\"boost\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rates of Allocation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=~\"boost\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC duration quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=~\"boost\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "booster-http",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory in Off-Heap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "go_memstats_mspan_inuse_bytes{job=~\"booster-http\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "go_memstats_mspan_sys_bytes{job=~\"booster-http\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "go_memstats_mcache_inuse_bytes{job=~\"booster-http\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "go_memstats_mcache_sys_bytes{job=~\"booster-http\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "go_memstats_buck_hash_sys_bytes{job=~\"booster-http\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "go_memstats_gc_sys_bytes{job=~\"booster-http\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "go_memstats_other_sys_bytes{job=~\"booster-http\"} - go_memstats_other_sys_bytes{job=~\"booster-http\"}",
       "legendFormat": "bytes of memory used for other runtime allocations"
      },
      {
       "expr": "go_memstats_next_gc_bytes{job=~\"booster-http\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Memory in Heap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{job=~\"booster-http\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "go_memstats_heap_sys_bytes{job=~\"booster-http\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "go_memstats_heap_idle_bytes{job=~\"booster-http\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "go_memstats_heap_inuse_bytes{job=~\"booster-http\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "go_memstats_heap_released_bytes{job=~\"booster-http\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Memory in Stack",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_stack_inuse_bytes{job=~\"booster-http\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "go_memstats_stack_sys_bytes{job=~\"booster-http\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Total Used Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "go_memstats_sys_bytes{job=~\"booster-http\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Number of Live Objects",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_memstats_mallocs_total{job=~\"booster-http\"} - go_memstats_frees_total{job=~\"booster-http\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rate of Objects Allocated",
     "type": "timeseries",
     "description": "shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(go_memstats_mallocs_total{job=~\"booster-http\"}[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rate of Pointer Dereferences",
     "type": "timeseries",
     "description": "go_memstats_lookups_total – counts how many pointer dereferences happened. This is a counter value so you can use rate() to lookups/s.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(go_memstats_lookups_total{job=~\"booster-http\"}[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_goroutines{job=~\"booster-http\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rates of Allocation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(go_memstats_alloc_bytes_total{job=~\"booster-http\"}[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GC duration quantile",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "go_gc_duration_seconds{job=~\"booster-http\"}",
       "legendFormat": "{{quantile}}"
      }
     ]
    }
   ]
  },
  {
   "title": "booster-bitswap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory in Off-Heap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "go_memstats_mspan_inuse_bytes{job=~\"booster-bitswap\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "go_memstats_mspan_sys_bytes{job=~\"booster-bitswap\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "go_memstats_mcache_inuse_bytes{job=~\"booster-bitswap\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "go_memstats_mcache_sys_bytes{job=~\"booster-bitswap\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "go_memstats_buck_hash_sys_bytes{job=~\"booster-bitswap\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "go_memstats_gc_sys_bytes{job=~\"booster-bitswap\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "go_memstats_other_sys_bytes{job=~\"booster-bitswap\"} - go_memstats_other_sys_bytes{job=~\"booster-bitswap\"}",
       "legendFormat": "bytes of memory used for other runtime allocations"
      },
      {
       "expr": "go_memstats_next_gc_bytes{job=~\"booster-bitswap\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Memory in Heap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{job=~\"booster-bitswap\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "go_memstats_heap_sys_bytes{job=~\"booster-bitswap\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "go_memstats_heap_idle_bytes{job=~\"booster-bitswap\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "go_memstats_heap_inuse_bytes{job=~\"booster-bitswap\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "go_memstats_heap_released_bytes{job=~\"booster-bitswap\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Memory in Stack",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_stack_inuse_bytes{job=~\"booster-bitswap\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "go_memstats_stack_sys_bytes{job=~\"booster-bitswap\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Total Used Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "go_memstats_sys_bytes{job=~\"booster-bitswap\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Number of Live Objects",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_memstats_mallocs_total{job=~\"booster-bitswap\"} - go_memstats_frees_total{job=~\"booster-bitswap\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rate of Objects Allocated",
     "type": "timeseries",
     "description": "shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(go_memstats_mallocs_total{job=~\"booster-bitswap\"}[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rate of Pointer Dereferences",
     "type": "timeseries",
     "description": "go_memstats_lookups_total – counts how many pointer dereferences happened. This is a counter value so you can use rate() to lookups/s.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(go_memstats_lookups_total{job=~\"booster-bitswap\"}[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "go_goroutines{job=~\"booster-bitswap\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rates of Allocation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(go_memstats_alloc_bytes_total{job=~\"booster-bitswap\"}[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GC duration quantile",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "go_gc_duration_seconds{job=~\"booster-bitswap\"}",
       "legendFormat": "{{quantile}}"
      }
     ]
    }
   ]
  }
 ]
}