name: Build

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:

jobs:
  build:
    name: Containers
    runs-on: ubuntu-latest
    env:
      LOTUS_TEST_IMAGE: 'filecoin/lotus-all-in-one:v1.23.2'
      FFI_BUILD_FROM_SOURCE: '0'
      DOCKER_BUILDKIT: '1'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update Boost modules
        run: make build/.update-modules
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        if: ${{ github.event_name != 'pull_request' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build boost-dev
        uses: ./.github/actions/container-builder
        with:
          name: boost-dev
          file: docker/devnet/Dockerfile.source
          target: boost-dev
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            LOTUS_TEST_IMAGE=${{ env.LOTUS_TEST_IMAGE }}
            FFI_BUILD_FROM_SOURCE=${{ env.FFI_BUILD_FROM_SOURCE }}
      - name: Build booster-http-dev
        uses: ./.github/actions/container-builder
        with:
          name: booster-http-dev
          file: docker/devnet/Dockerfile.source
          target: booster-http-dev
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            LOTUS_TEST_IMAGE=${{ env.LOTUS_TEST_IMAGE }}
            FFI_BUILD_FROM_SOURCE=${{ env.FFI_BUILD_FROM_SOURCE }}
      - name: Build booster-bitswap-dev
        uses: ./.github/actions/container-builder
        with:
          name: booster-bitswap-dev
          file: docker/devnet/Dockerfile.source
          target: booster-bitswap-dev
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            LOTUS_TEST_IMAGE=${{ env.LOTUS_TEST_IMAGE }}
            FFI_BUILD_FROM_SOURCE=${{ env.FFI_BUILD_FROM_SOURCE }}
      - name: Build lotus-dev
        uses: ./.github/actions/container-builder
        with:
          name: lotus-dev
          context: ./docker/devnet/lotus
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            LOTUS_TEST_IMAGE=${{ env.LOTUS_TEST_IMAGE }}
            FFI_BUILD_FROM_SOURCE=${{ env.FFI_BUILD_FROM_SOURCE }}
      - name: Build lotus-miner-dev
        uses: ./.github/actions/container-builder
        with:
          name: lotus-miner-dev
          context: ./docker/devnet/lotus-miner
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            LOTUS_TEST_IMAGE=${{ env.LOTUS_TEST_IMAGE }}
            FFI_BUILD_FROM_SOURCE=${{ env.FFI_BUILD_FROM_SOURCE }}